version: '3.9'

x-common: &common
   restart: always

services:
  backend:
    <<: *common
    build: .
    environment:
      DATA_PATH: ${DATA_PATH?}
      LOG_LEVEL: ${LOG_LEVEL?}
      UVICORN_PORT: ${PORT?}
      UVICORN_WORKERS: ${WORKERS:-1}
    container_name: hackathon
    ports:
      - "${PORT?}:${PORT?}"
    volumes:
      - ${DATA_PATH?}:/app/data
